#!/bin/bash
set +x

#This script takes a file and inserts the data into the db table.
# This file is generated by a front end script like fetch_revs.sh

if [  $# -lt 2 ]; then
   echo "Usage: $0 <infile> <table>"
   echo "   This script loops through <infile> and inserts in into the db <table>"
   echo ""
   exit 1
fi


infile=$1
table=$2
user="update_avail"
passwd="update_avail"
while read line
do 
   echo -e "$line \n"
   #rev=$(echo "$line | awk -F\| '{print $1}')
   #echo -e "\"$line\" | awk -F\| '{print \$1}')"
   crev=$(echo -e $line | awk -F'|' '{print $1}')
   pver=$(echo -e $line | awk -F'|' '{print $2}')
   pver=$(echo $pver | sed "s/ //g")
   prel=$(echo -e $line | awk -F'|' '{print $3}')
   prel=$(echo $prel | sed "s/ //g")
   cuser=$(echo -e $line | awk -F'|' '{print $4}')
   cuser=$(echo $cuser | sed "s/ //g")
   cdate=$(echo -e $line | awk -F'|' '{print $5}')
   ctime=$(echo -e $line | awk -F'|' '{print $6}')
   ctz=$(echo -e $line | awk -F'|' '{print $7}')
   cpkg=$(echo -e $line | awk -F'|' '{print $8}')
   cpkg=$(echo $cpkg | sed "s/ //g")
   psum=$(echo -e $line | awk -F'|' '{print $9}')
   psum=$(echo $psum | sed "s/'/\\\'/g")
   cmsg=$(echo -e $line | awk -F'|' '{print $10}')
   cmsg=$(echo $cmsg | sed "s/'/\\\'/g")
   echo "Rev=$crev"
   echo "User=$cuser"
   echo "Date=$cdate"
   echo "Time=$ctime"
   echo "Time zone=$ctz"
   echo "Pkg=$cpkg"
   echo "Msg=$cmsg"

   # first we remove old packages for which we have a newer or existing commit. We only allow building the latest commit of a pkg.
   #mysql -u update_avail -pupdate_avail BS -e "delete from pkg_commits where pkg_name='$cpkg' and commit<=$crev"
   mysql -u update_pkgs -pupdate_pkgs BS -e "delete from $table where pkg_name='$cpkg' and commit<=$crev"
   # now put it in the list of pkgs available for building
   #mysql -u update_avail -pupdate_avail BS -e "insert into  pkg_commits (pkg_name,pkg_ver,pkg_rel,commit,committer,commit_time,pkg_summary,log_msg, current_status, TS) values ('$cpkg','$pver','$prel', $crev,'$cuser','$cdate $ctime','$psum','$cmsg', 'Avail for Building', now())"
   mysql -u update_pkgs -pupdate_pkgs BS -e "insert into $table (pkg_name,pkg_ver,pkg_rel,commit,committer,commit_time,pkg_summary,log_msg, TS) values ('$cpkg','$pver','$prel', $crev,'$cuser','$cdate $ctime','$psum','$cmsg', now())"
done < $infile


