#!/bin/bash

# name of this script
myname=$(basename $0)
#
# name of the .mo file for translations
moname="pkgutils"
#

# This function is for giving the script i18n support.
__ () {
	local gettextopts="-d $moname -e --"
        local TEXT=`gettext $gettextopts "$1"`		# Unfortunately `` and $() remove any trailing newlines
							# so, if one is present, it must be restored.
							# Please, note that if more newlines are present
							# they will be reduced to one.
	[ "$(echo $1|grep "\\n$")" ] && TEXT="$TEXT\n"	# If $1 ends with \n append \n to TEXT
	[[ $1 = *$'\n' ]] && TEXT="$TEXT\n"		# If $1 ends with newline append \n to TEXT
	shift
	printf -- "$TEXT" "$@"
}

while read f; do
	if [ -L "$f" ]; then
		r=$(readlink "$f")
		if ! [ -f "$r" ]; then
			[ "$1" = "-v" ] && __ "Unlinking '%s'\n" "$f"
			unlink "$f"
		fi
	fi
done < <(ls -1)
